# Generated by Django 2.2.1 on 2019-06-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Icone'),
        ),
    ]
